### ISSUE TITLE
http请求解析

### ISSUE THREAD

**Issue by xchao263** [someus/another-tutorial-about-java-web#1]
您好，看到你这篇文章使对http有了一定了解，其本质还是socket程序，自己也写过一些socket相关的程序，对于客户端如何与服务器端交流通讯也有一定了解，能够理解您这篇文章里的服务器端实现代码，但不理解您的测试程序访问方式，按标准socket访问只需要指定ip及端口即可，而您的是 http://ip:端口，对于这个程序，不就是模拟出http服务器吗，此时在这里又指明了http ，这似乎又点说不通啊，还望指点赐教，谢谢！

**Comment by letiantian** [comment]
写出来不就是让浏览器通过http协议请求的嘛。可以去了解下http发起请求的流程的原理。
